// <auto-generated />
namespace MovieTheater.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class init1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init1));
        
        string IMigrationMetadata.Id
        {
            get { return "201409271905176_init1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
